version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db_Gwenael
    volumes:
      - mssql-volume:/var/opt/mssql
    environment:
        SA_PASSWORD: "q8TewW25C4j3sCPVWfH@!"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  app:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: Gwenael
    ports:
      - '5000:80'
      - '5001:443'
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  mssql-volume:
